
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://titanium-cranium.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-72745580-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Brendan J. O'Brien"
title: "{ titanium cranium }"
description: "Blog and website of Brendan J. O'Brien, creating worlds for mind and machine alike."
keywords: "Brendan O'Brien, Polyglot Web Developer, Melbourne, Australia"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Welcome to the <b>titanium cranium</b>"
  - text: "It's what's <i>inside</i> that counts..."

me-img: "/img/TC_brain_logo.png"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 50

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "titaniumcraniumgithubio"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/studying.jpg"
    date: "1987-1997"
    description: "Studying hard: BA (Psychology) & PhD (Neuroscience)"
  - image: "/img/timeline/eye_glyph.jpg"
    date: "1997-2003"
    description: "Postdoctoral training in vision science"
  - image: "/img/timeline/me.png"
    date: "2003-2013"
    description: "Lecturing at Universities Down Under"
  - image: "/img/timeline/writing.png"
    date: "2013-2015"
    description: "Writing & publishing eBooks"
  - image: "/img/timeline/ruby.png"
    date: "2015-2016"
    description: "Metamorphosis: From Neurocientist to Programmer"
  - image: "/img/timeline/java.png"
    date: "2016-2017"
    description: "Software Engineer at Gate121"
  - image: "/img/timeline/python.jpeg"
    date: "2017-present"
    description: "Software Engineer/Data Scientist at Factil.io"
  - image: "/img/timeline/reactjs.jpeg"
    date: "2018-present"
    description: "Developer at Envato"

# First image of the Timeline

timeline-img: "/img/timeline/helmet.png"

###########
# Contact #
###########

email: "b.obrien@me.com"

##################
# Social Buttons #
##################

social:
  # - title: "facebook"
  #   url: "https://facebook.com/"
  - title: "linkedin"
    url: "https://au.linkedin.com/in/bjobrienphd"
  - title: "github"
    url: "https://github.com/titanium-cranium"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/cv/bjobrien"
  - title: "amazon"
    url: "http://www.amazon.com/-/e/B00Q5XS2CO"
  - title: "university"
    url: "https://scholar.google.com.au/citations?user=qORoKiYAAAAJ&hl=en"
  # - title: "twitter"
  #   url: "https://twitter.com/@bobrien69"

# Need to fix the xml
  # - title: "rss"
  #   url: "/feed.xml"

  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"


############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
